### ISSUE TITLE
Endpoint: PUT - Arquivar log de erro

### ISSUE THREAD

**Issue by matancredi** [mayaracsferreira/error-central#10]
Regras:

- Deve ser possível arquivar um dado log de erro
- O arquivamento será feito setando sua flag como false

**Comment by tabskey** [comment]
Não consegui fazer nenhum PUT.
Erro 405

**Comment by matancredi** [comment]
@tabskey lá no postman tem que colocar PUT do lado da URL... esse erro 405 dá quando a gente coloca o nome errado (POST/PUT/GET)

**Comment by tabskey** [comment]
Puts, só joguei o link limpo
