### ISSUE TITLE
Criar controllers

### ISSUE THREAD

**Issue by matancredi** [mayaracsferreira/error-central#18]

**Comment by tabskey** [comment]
Infelizmente não consegui dar Delete.

**Comment by matancredi** [comment]
@tabskey vê se não é a mesma coisa do erro 405 (tá colocando DELETE do lado da url no postman?)

**Comment by tabskey** [comment]
Consertado, o DELETE funciona a partir do ID, seria algo como api/eventlog/numerodaid.
Só pra registrar o/
