### ISSUE TITLE
Endpoint: POST - Cadastro de novo usuário

### ISSUE THREAD

**Issue by matancredi** [mayaracsferreira/error-central#7]
Regras:

- Um novo usuário deve poder fazer um cadastro no sistema
- Dados obrigatórios: email e senha
- Dados opcionais: (verificar se vamos colocar nome, data de nascimento ou outros)
- Os dados devem ser salvos na tabela usuário
- A senha deverá ser criptografada antes de ser gravada no banco (sugestão: pesquisar por sha2)

A autenticação depende da conclusão dessa issue

**Comment by tabskey** [comment]
Eu achei um Design Pattern pra ajudar https://www.fabiosilvalima.net/jwt-autenticacao-asp-net-core-identity/

https://www.fabiosilvalima.net/wp-content/uploads/2019/04/Programacao-no-Mundo-Real-Design-Patterns-Vol-1-Edicao-2-2019-04-01.pdf

**Comment by matancredi** [comment]
Update: Fiz a maioria dessas coisas na branch do login, falta só criptografar a senha
